{% set name = "geetools" %}
{% set version = "1.15.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geetools-{{ version }}.tar.gz
  sha256: 8fadcd3035e74696661fe1d3d410264e88af8c86f1ca4763fd77517e32ebae02

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - earthengine-api >=1
    - requests
    - pandas
    - geopandas
    - deprecated
    - ee_extra
    - xee >=0.0.11
    - yamlable
    - matplotlib-base
    - anyascii

test:
  imports:
    - geetools
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: A collection of tools to work with Google Earth Engine Python API
  license: MIT
  license_file: LICENSE
  home: https://geetools.readthedocs.io

extra:
  recipe-maintainers:
    - 12rambau
    - fitoprincipe
