{% set name = "geetools" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geetools-{{ version }}.tar.gz
  sha256: a436f6396a244eedadca155d7ec913cb2f8cb4c856e2be034b41ebce87c9849b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - earthengine-api
    - requests
    - pandas
    - geopandas
    - deprecated
    - ee_extra
    - xee

test:
  imports:
    - geetools
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A collection of tools to work with Google Earth Engine Python API
  license: MIT
  license_file: LICENSE
  home: https://gee-tools.readthedocs.io

extra:
  recipe-maintainers:
    - 12rambau
    - fitoprincipe
