{% set name = "geetools" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geetools-{{ version }}.tar.gz
  sha256: a4860d1a46b723cd6768864942ed92a6ba5dfa45db018cc8981085286e749c39

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - earthengine-api >=1
    - requests
    - pandas
    - geopandas
    - deprecated
    - ee_extra
    - xee >=0.0.11
    - yamlable
    - matplotlib-base
    - anyascii

test:
  imports:
    - geetools
  #commands:
  #  - pip check
  requires:
    - pip

about:
  summary: A collection of tools to work with Google Earth Engine Python API
  license: MIT
  license_file: LICENSE
  home: https://gee-tools.readthedocs.io

extra:
  recipe-maintainers:
    - 12rambau
    - fitoprincipe
